apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: fedora-qemu-user-static
spec:
  selector:
    matchLabels:
      name: fedora-qemu-user-static
  template:
    metadata:
      labels:
        name: fedora-qemu-user-static
    spec:
      volumes:
      - name: hostbindir # a directory on the host which won't persist
        hostPath:
          path: /run/fedora-qemu-user-static
      initContainers:
      - name: fedora-qemu-user-static
        image: ghcr.io/nalind/fedora-qemu-user-static
        imagePullPolicy: IfNotPresent
        securityContext:
          privileged: true
        command:
        - /entrypoint.sh
        - register
        volumeMounts:
        - name: hostbindir # mount that non-persistent directory into the container so that we can copy interpreters into it
          mountPath: /usr/local/bin
        env:
        - name: BINDIR # entrypoint.sh will copy interpreters to this directory in the container
          value: /usr/local/bin
        - name: CHCON # entrypoint.sh will run "chcon" with this as its argument for each interpreter after copying
          value: -t bin_t
      containers:
      - image: k8s.gcr.io/pause:3.2
        name: pause
      nodeSelector:
        kubernetes.io/os: linux
